# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nsnam/ns-3-dev-git'
        ref: 'master'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
       path: 'src/quic' 
    
    - name: check that quic is correctly installed
      run: ls src/ | grep quic

    - name: enable only quic
      run: printf "#! /usr/bin/env python \n modules_enabled = ['quic', 'applications']" > .ns3rc
      
    - name: build and run the tests
      run: ./waf configure --enable-examples --enable-tests && ./waf build && ./test.py
      
    - name: build and run the tests with optimized build
      run: ./waf configure --enable-examples --enable-tests --build-profile=optimized && ./waf build && ./test.py
